services:
  rest-on-couch:
    build: ./rest-on-couch
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: 1234
      DEBUG: couch:*
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS:?Provide the origins in your .env file}
    depends_on:
      - couchdb
    restart: unless-stopped
    ports:
      - 127.0.0.1:3000:3000
  couchdb:
    image: docker.io/couchdb:3.4
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: 1234
    volumes:
      - ./couchdb-data:/opt/couchdb/data
      - ./config/couch.ini:/opt/couchdb/etc/local.d/couch.ini
    restart: unless-stopped
